experiments:
  - name: Model_Medium_Adam_Aug_final
    num_conv_blocks: 3
    initial_filters: 32
    kernel_size: [3, 3]
    dense_units: 256
    dropout_rate: 0.2
    optimizer_type: Adam
    learning_rate: 0.001
    epochs: 150
    patience: 15
    batch_size: 128
    augmentation: True